run_name: 'gauss_uberseg'
base_dir: '/projects/superbit/repos/superbit-metacal/runs/gauss_uberseg/'
nfw_dir: '/projects/superbit/repos/superbit-metacal/runs/nfw_truth/'
gs_base_config: '/projects/superbit/repos/superbit-metacal/configs/gauss-uberseg-gs.yaml'
mass_bins: [2.5e14, 4.1e14, 5.8e14, 7.8e14, 1.6e15] # Msol / h; must have decimal!
z_bins: [0.075, 0.25, 0.45]
realizations: 30
ncores_per_job: 48
memory_per_job: 64 
vb: False
run_diagnostics: True
overwrite: True
master_seed: 4681084119
